const actions = {
  PROPAGATE_MOVIES: 'PROPAGATE_MOVIES',
  PROPAGATE_SINGLE_MOVIE: 'PROPAGATE_SINGLE_MOVIE',

  ERASE_SINGLE_MOVIE: 'ERASE_SINGLE_MOVIE',
  SHOW_SINGLE_MOVIE: 'SHOW_SINGLE_MOVIE',

  SWAP_SEARCH_BY: 'SWAP_SEARCH_BY',
  SWAP_SORT_BY: 'SWAP_SORT_BY',
};

export default actions;
