export const ACTIONS = {
  CHANGE_INPUT_STRING: 'CHANGE_INPUT_STRING',
  FETCH_MOVIES: 'FETCH_MOVIES',
  FETCH_SINGLE_MOVIE: 'FETCH_SINGLE_MOVIE',
  SHOW_SINGLE_MOVIE: 'SHOW_SINGLE_MOVIE',
};

export const COLOR = {
  NETFLIX_RED: '#ff594b',
  NETFLIX_GREY: '#464646',
};
