/* action types */
export const ACTIONS = {
  PROPAGATE_MOVIES: 'PROPAGATE_MOVIES',
  SHOW_SEARCH_BLOCK: 'SHOW_SEARCH_BLOCK',
  SHOW_NO_MOVIES_FOUND: 'SHOW_NO_MOVIES_FOUND',

  PROPAGATE_SINGLE_MOVIE: 'PROPAGATE_SINGLE_MOVIE',
  SHOW_SINGLE_MOVIE: 'SHOW_SINGLE_MOVIE',

  SWAP_SEARCH_BY: 'SWAP_SEARCH_BY',
  SWAP_SORT_BY: 'SWAP_SORT_BY',
};

export const COLOR = {
  NETFLIX_RED: '#ff594b',
  NETFLIX_GREY: '#464646',
};
